#!/usr/bin/env python3

import colors as c
import random

# Attacker's stats

print(c.clear)
print("Welcome to the Fire Emblem Battle Calculator!")
print("Please enter the attacker's stats.")
attacker_name = input("Attacker's name > ")
attacker_boss = input("Is this unit a boss? > ").lower()
attacker_class = input("Attacker's class > ").lower()
attacker_current_hp = int(input("Attacker's current HP > "))
attacker_max_hp = int(input("Attacker's max HP > "))
attacker_exp = int(input("Attacker's current EXP > "))
attacker_level = int(input("Attacker's level > "))
attacker_strength = int(input("Attacker's Strength > "))
attacker_magic = int(input("Attacker's Magic > "))
attacker_skill = int(input("Attacker's Skill > "))
attacker_speed = int(input("Attacker's Speed > "))
attacker_luck = int(input("Attacker's Luck > "))
attacker_defense = int(input("Attacker's Defense > "))
attacker_resistance = int(input("Attacker's Resistance > "))
attacker_weapon_type = input("Attacker's weapon type > ").lower()
attacker_weapon_uses = int(input("Attacker's weapon's remaining uses > "))
attacker_weapon_might = int(input("Attacker's weapon's Might > "))
attacker_weapon_hit = int(input("Attacker's weapon's Hit % > "))
attacker_weapon_crit = int(input("Attacker's weapon's Critical Rate > "))
attacker_weapon_range = input("Attacker's weapon's Range > ")
attacker_weapon_effect = input("Attacker's weapon's added effect(s) > ").lower()
attacker_hp_growth = int(input("Attacker's HP growth > "))
attacker_strength_growth = int(input("Attacker's Strength growth > "))
attacker_magic_growth = int(input("Attacker's Magic growth > "))
attacker_skill_growth = int(input("Attacker's Skill growth > "))
attacker_speed_growth = int(input("Attacker's Speed growth > "))
attacker_luck_growth = int(input("Attacker's Luck growth > "))
attacker_defense_growth = int(input("Attacker's Defense growth > "))
attacker_resistance_growth = int(input("Attacker's Resistance growth > "))

# Attacker's attack type (physical or magical)

if attacker_weapon_type == "tome":
  attacker_strength = attacker_magic

# Defender's stats

print(c.clear)
print("Please enter the defender's stats.")
defender_name = input("Defender's name > ")
defender_boss = input("Is this unit a boss? > ").lower()
defender_class = input("Defender's class > ").lower()
defender_current_hp = int(input("Defender's current HP > "))
defender_max_hp = int(input("Defender's max HP > "))
defender_exp = int(input("Defender's current EXP > "))
defender_level = int(input("Defender's level > "))
defender_strength = int(input("Defender's Strength > "))
defender_magic = int(input("Defender's Magic > "))
defender_skill = int(input("Defender's Skill > "))
defender_speed = int(input("Defender's Speed > "))
defender_luck = int(input("Defender's Luck > "))
defender_defense = int(input("Defender's Defense > "))
defender_resistance = int(input("Defender's Resistance > "))
defender_weapon_type = input("Defender's weapon type > ").lower()
defender_weapon_uses = int(input("Defender's weapon's remaining uses > "))
defender_weapon_might = int(input("Defender's weapon's Might > "))
defender_weapon_hit = int(input("Defender's weapon's Hit % > "))
defender_weapon_crit = int(input("Defender's weapon's Critical Rate > "))
defender_weapon_range = input("Defender's weapon's Range > ")
defender_weapon_effect = input("Defender's weapon's added effect(s) > ").lower()
defender_hp_growth = int(input("Attacker's HP growth > "))
defender_strength_growth = int(input("Attacker's Strength growth > "))
defender_magic_growth = int(input("Attacker's Magic growth > "))
defender_skill_growth = int(input("Attacker's Skill growth > "))
defender_speed_growth = int(input("Attacker's Speed growth > "))
defender_luck_growth = int(input("Attacker's Luck growth > "))
defender_defense_growth = int(input("Attacker's Defense growth > "))
defender_resistance_growth = int(input("Attacker's Resistance growth > "))

# Defender's attack type (physical or magical) and attacker's defense type (physical or magical)

if defender_weapon_type == "tome":
  defender_strength = defender_magic
  attacker_defense = attacker_resistance

# Defender's defense type (physical or magical)

if attacker_weapon_type == "tome":
  defender_defense = defender_resistance

# Attacker's experience-related formulas

  # Class Power

if attacker_class == "villager" or attacker_class == "entombed" or attacker_class == "mirage":
  attacker_class_power = 1
if attacker_class == "cleric" or attacker_class == "priest" or attacker_class == "soldier" or attacker_class == "troubadour" or attacker_class == "thief" or attacker_class == "dancer" or attacker_class == "taguel" or attacker_class == "manakete":
  attacker_class_power = 2
elif attacker_class == "grima":
  attacker_class_power = 5
else:
  attacker_class_power = 3

  # Class Bonus A

if attacker_class == "great lord" or attacker_class == "grandmaster" or attacker_class == "paladin" or attacker_class == "general" or attacker_class == "great knight" or attacker_class == "swordmaster" or attacker_class == "trickster" or attacker_class == "assassin" or attacker_class == "berserker" or attacker_class == "warrior" or attacker_class == "hero" or attacker_class == "sniper" or attacker_class == "bow knight" or attacker_class == "sorcerer" or attacker_class == "sage" or attacker_class == "dark knight" or attacker_class == "war cleric" or attacker_class == "war monk" or attacker_class == "valkyrie" or attacker_class == "falcon knight" or attacker_class == "dark flier" or attacker_class == "wyvern lord" or attacker_class == "griffon rider" or attacker_class == "entombed":
  attacker_class_bonus_a = 20
else:
  attacker_class_bonus_a = 0

  # Class Bonus B

if attacker_class == "assassin" or defender_class == "trickster" or defender_class == "war monk" or attacker_class == "war cleric" or attacker_class == "valkyrie":
  attacker_class_bonus_b = 40
elif attacker_class == "great lord" or attacker_class == "grandmaster" or attacker_class == "paladin" or attacker_class == "general" or attacker_class == "great knight" or attacker_class == "swordmaster" or attacker_class == "berserker" or attacker_class == "warrior" or attacker_class == "hero" or attacker_class == "sniper" or attacker_class == "bow knight" or attacker_class == "sorcerer" or attacker_class == "sage" or attacker_class == "dark knight" or attacker_class == "falcon knight" or attacker_class == "dark flier" or attacker_class == "wyvern lord" or attacker_class == "griffon rider" or attacker_class == "entombed":
  attacker_class_bonus_b = 60
else:
  attacker_class_bonus_b = 0

  # Boss Bonus

if attacker_boss == "yes":
  attacker_boss_bonus = 40
else:
  attacker_boss_bonus = 0

  # Thief Bonus

if attacker_class == "thief" or attacker_class == "assassin" or attacker_class == "trickster":
  attacker_thief_bonus = 20
else:
  attacker_thief_bonus = 0

# Defender's experience-related formulas

  # Class Power

if defender_class == "villager" or defender_class == "entombed" or defender_class == "mirage":
  defender_class_power = 1
if defender_class == "cleric" or defender_class == "priest" or defender_class == "soldier" or defender_class == "troubadour" or defender_class == "thief" or defender_class == "dancer" or defender_class == "taguel" or defender_class == "manakete":
  defender_class_power = 2
elif defender_class == "grima":
  defender_class_power = 5
else:
  defender_class_power = 3

  # Class Bonus A

if defender_class == "great lord" or defender_class == "grandmaster" or defender_class == "paladin" or defender_class == "general" or defender_class == "great knight" or defender_class == "swordmaster" or defender_class == "trickster" or defender_class == "assassin" or defender_class == "berserker" or defender_class == "warrior" or defender_class == "hero" or defender_class == "sniper" or defender_class == "bow knight" or defender_class == "sorcerer" or defender_class == "sage" or defender_class == "dark knight" or defender_class == "war cleric" or defender_class == "war monk" or defender_class == "valkyrie" or defender_class == "falcon knight" or defender_class == "dark flier" or defender_class == "wyvern lord" or defender_class == "griffon rider" or defender_class == "entombed":
  defender_class_bonus_a = 20
else:
  defender_class_bonus_a = 0

  # Class Bonus B

if defender_class == "assassin" or defender_class == "trickster" or defender_class == "war monk" or defender_class == "war cleric" or defender_class == "valkyrie":
  defender_class_bonus_b = 40
elif defender_class == "great lord" or defender_class == "grandmaster" or defender_class == "paladin" or defender_class == "general" or defender_class == "great knight" or defender_class == "swordmaster" or defender_class == "berserker" or defender_class == "warrior" or defender_class == "hero" or defender_class == "sniper" or defender_class == "bow knight" or defender_class == "sorcerer" or defender_class == "sage" or defender_class == "dark knight" or defender_class == "valkyrie" or defender_class == "falcon knight" or defender_class == "dark flier" or defender_class == "wyvern lord" or defender_class == "griffon rider" or defender_class == "entombed":
  defender_class_bonus_b = 60
else:
  defender_class_bonus_b = 0

  # Boss Bonus

if defender_boss == "yes":
  defender_boss_bonus = 40
else:
  defender_boss_bonus = 0

  # Thief Bonus

if defender_class == "thief" or defender_class == "assassin" or defender_class == "trickster":
  defender_thief_bonus = 20
else:
  defender_thief_bonus = 0

# Battle Formulas

# Number of Attacks

if attacker_speed >= defender_speed + 5:
  attacker_attack_times = 2
  defender_attack_times = 1
elif defender_speed >= attacker_speed + 5:
  attacker_attack_times = 1
  defender_attack_times = 2
else:
  attacker_attack_times = 1
  defender_attack_times = 1

# Hit Rate

attacker_hit_rate = attacker_weapon_hit + attacker_skill * 2 + int(attacker_luck / 2)
defender_hit_rate = defender_weapon_hit + defender_skill * 2 + int(defender_luck / 2)

# Evade

attacker_evade = attacker_speed + int(attacker_luck / 2)
defender_evade = defender_speed + int(defender_luck / 2)

# Accuracy

attacker_accuracy = attacker_hit_rate - defender_evade
defender_accuracy = defender_hit_rate - defender_evade

# Attack Power

attacker_attack_power = attacker_strength + attacker_weapon_might
defender_attack_power = defender_strength + defender_weapon_might

# Defense Power

attacker_defense_power = attacker_defense
defender_defense_power = defender_defense

# Damage

attacker_damage = attacker_attack_power - defender_defense_power
defender_damage = defender_attack_power - attacker_defense_power

# Critical Rate

attacker_crit_rate = attacker_weapon_crit + int(attacker_skill / 2)
defender_crit_rate = defender_weapon_crit + int(defender_skill / 2)

# Critical Evade

attacker_crit_evade = attacker_luck
defender_crit_evade = defender_luck

# Critical Chance

attacker_crit_chance = attacker_crit_rate - defender_crit_evade
defender_crit_chance = defender_crit_rate - attacker_crit_evade

# Critical Damage

attacker_crit_damage = attacker_damage * 3
defender_crit_damage = defender_damage * 3

# Battle Preview

print(c.clear)
print("Battle Preview:")
print(attacker_name + ":")
print("Damage: " + str(attacker_damage) + "x" + str(attacker_attack_times))
print("Accuracy: " + str(attacker_accuracy) + "%")
print("Crit: " + str(attacker_crit_chance) + "%")
print(defender_name + ":")
print("Damage: " + str(defender_damage) + "x" + str(defender_attack_times))
print("Accuracy: " + str(defender_accuracy) + "%")
print("Crit: " + str(defender_crit_chance) + "%")

# Battle

battle_ready = input("Initiate the battle? > ")
if battle_ready == "yes":
  print(c.clear)

  # Attacker and defender attack once

  # Attacker's attack

  if attacker_attack_times == 1 and defender_attack_times == 1:
      
      # Attacker's crit roll

      attacker_crit_roll = random.randint(1,100)

      # Attacker gets a crit

      if attacker_crit_roll <= attacker_crit_chance:
          print(attacker_name + " got a critical hit!")
          attacker_hit_roll = random.randint(1,100)
          
          # Attacker hits crit

          if attacker_hit_roll <= attacker_accuracy:
              defender_current_hp = defender_current_hp - attacker_crit_damage
              attacker_weapon_uses -= 1
              print(defender_name + " took " + str(attacker_crit_damage) + " damage!")
              if attacker_weapon_uses <= 0:
                  print(attacker_name + "'s weapon broke!")
          
          # Attacker misses crit

          else:
              print(attacker_name + " missed!")
      
      # Attacker doesn't get a crit

      else:
          attacker_hit_roll = random.randint(1,100)
          
          # Attacker hits

          if attacker_hit_roll <= attacker_accuracy:
              defender_current_hp = defender_current_hp - attacker_damage
              print(attacker_name + " attacks!")
              print(defender_name + " took " + str(attacker_damage) + " damage!")
              attacker_weapon_uses -= 1
              if attacker_weapon_uses <= 0:
                  print(attacker_name + "'s weapon broke!")
          
          # Attacker misses

          else:
              print(attacker_name + " missed!")

      # Defender's attack

      if defender_current_hp > 0:
          
          # Defender's crit roll

          defender_crit_roll = random.randint(1,100)

          # Defender gets a crit

          if defender_crit_roll <= defender_crit_chance:
              print(defender_name + " got a critical hit!")
              defender_hit_roll = random.randint(1,100)

              # Defender hits crit

              if defender_hit_roll <= defender_accuracy:
                  attacker_current_hp = attacker_current_hp - defender_crit_damage
                  print(attacker_name + " took " + str(defender_crit_damage) + " damage!")
                  defender_weapon_uses -= 1
                  if defender_weapon_uses <= 0:
                      print(defender_name + "'s weapon broke!")

              # Defender misses crit

              else:
                  print(defender_name + " missed!")

          # Defender doesn't get a crit

          else:
              defender_hit_roll = random.randint(1,100)

              # Defender hits attack

              if defender_hit_roll <= defender_accuracy:
                  attacker_current_hp = attacker_current_hp - defender_damage
                  print(defender_name + " attacks!")
                  print(attacker_name + " took " + str(defender_damage) + " damage!")
                  defender_weapon_uses -= 1
                  if defender_weapon_uses <= 0:
                      print(defender_name + "'s weapon broke!")

              # Defender misses attack
              
              else:
                  print(defender_name + " missed!")
      
      # Defender is dead
      
      else:
          print(defender_name + " has died.")
          print(attacker_name + " wins!")

      # Attacker is dead

      if attacker_current_hp <= 0:
          print(attacker_name + " has died.")
          print(defender_name + " wins!")

      # Attacker's remaining HP

      print(attacker_name + " has " + str(attacker_current_hp) + " HP remaining.")
      
      # Defender's remaining HP
      
      print(defender_name + " has " + str(defender_current_hp) + " HP remaining.")
      
      # Attacker's weapon's remaining uses

      if attacker_weapon_uses > 1 or attacker_weapon_uses < 1:
          print(attacker_name + "'s weapon has " + str(attacker_weapon_uses) + " uses remaining.")
      else: 
          print(attacker_name + "'s weapon has " + str(attacker_weapon_uses) + " use remaining.")
      
      # Defender's weapon's remaining uses

      if defender_weapon_uses > 1 or defender_weapon_uses < 1:    
          print(defender_name + "'s weapon has " + str(defender_weapon_uses) + " uses remaining.")
      else:
          print(defender_name + "'s weapon has " + str(defender_weapon_uses) + " use remaining.")
      
      # Experience Points

      # Attacker
      
      # Attacker's max level is 30

      #if attacker_class == "dancer" or attacker_class == "manakete" or attacker_class == "taguel" or attacker_class == "conqueror" or attacker_class == "dread fighter" or attacker_class == "bride" or attacker_class == "villager" or attacker_class == "lodestar" or attacker_class == "soldier" or attacker_class == "merchant" or attacker_class == "revenant" or attacker_class == "entombed" or attacker_class == "grima" or attacker_class == "mirage":
      attacker_classes = ["dancer","manakete","taguel","conqueror","dread fighter",
                          "bride","villager","lodestar","soldier","merchant","revenant",
                          "entombed","grima","mirage"]
      if attacker_class in attacker_classes:


          if attacker_current_hp > 0:
         
              if attacker_level < 30:
          
                  # Attacker hits
          
                  if attacker_hit_roll <= attacker_accuracy:
              
                      # Attacker doesn't kill

                      if defender_current_hp > 0:
                  
                          # Experience from dealing damage

                          attacker_exp_gained = int((31 + (defender_level + defender_class_bonus_a) - (attacker_level + attacker_class_bonus_a))/attacker_class_power)
                          attacker_exp += attacker_exp_gained
                          
                          # Leveling up

                          attacker_level_ups = int(attacker_exp/100)
                          attacker_exp -= attacker_level_ups * 100
                          
                          # HP

                          attacker_hp_levels = int(attacker_hp_growth/100)
                          attacker_hp_growth -= attacker_hp_levels * 100
                          
                          # Strength

                          attacker_strength_levels = int(attacker_strength_growth/100)
                          attacker_strength_growth -= attacker_strength_levels * 100
                          
                          # Magic

                          attacker_magic_levels = int(attacker_magic_growth/100)
                          attacker_magic_growth -= attacker_magic_levels * 100
                          
                          # Skill

                          attacker_skill_levels = int(attacker_skill_growth/100)
                          attacker_skill_growth -= attacker_skill_levels * 100
                          
                          # Speed

                          attacker_speed_levels = int(attacker_speed_growth/100)
                          attacker_speed_growth -= attacker_speed_levels * 100
                          
                          # Luck

                          attacker_luck_levels = int(attacker_luck_growth/100)
                          attacker_luck_growth -= attacker_luck_levels * 100
                          
                          # Defense

                          attacker_defense_levels = int(attacker_defense_growth/100)
                          attacker_defense_growth -= attacker_defense_levels * 100
                          
                          # Resistance

                          attacker_resistance_levels = int(attacker_resistance_growth/100)
                          attacker_resistance_growth -= attacker_resistance_levels * 100
                          
                          # Level ups

                          while attacker_level_ups > 0:
                              attacker_level += 1
                              print(attacker_name + " leveled up!")
                              print(attacker_name + "'s level is now " + str(attacker_level) + ".")
                              attacker_level_ups -= 1
                              
                              # HP

                              while attacker_hp_levels > 0:
                                  attacker_max_hp += 1
                                  attacker_hp_levels -= 1
                              attacker_hp_roll = random.randint(1,100)
                              if attacker_hp_roll <= attacker_hp_growth:
                                  attacker_max_hp += 1
                              print(attacker_name + "'s max HP is now " + str(attacker_max_hp) + ".")
                              
                              # Strength

                              while attacker_strength_levels > 0:
                                  attacker_strength += 1
                                  attacker_strength_levels -= 1
                              attacker_strength_roll = random.randint(1,100)
                              if attacker_strength_roll <= attacker_strength_growth:
                                  attacker_strength += 1
                              print(attacker_name + "'s Strength is now " + str(attacker_strength) + ".")
                              
                              # Magic

                              while attacker_magic_levels > 0:
                                  attacker_magic += 1
                                  attacker_magic_levels -= 1
                              attacker_magic_roll = random.randint(1,100)
                              if attacker_magic_roll <= attacker_magic_growth:
                                  attacker_magic += 1
                              print(attacker_name + "'s Magic is now " + str(attacker_magic) + ".")
                              
                              # Skill

                              while attacker_skill_levels > 0:
                                  attacker_skill += 1
                                  attacker_skill_levels -= 1
                              attacker_skill_roll = random.randint(1,100)
                              if attacker_skill_roll <= attacker_skill_growth:
                                  attacker_skill += 1
                              print(attacker_name + "'s Skill is now " + str(attacker_skill) + ".")
                              
                              # Speed

                              while attacker_speed_levels > 0:
                                  attacker_speed += 1
                                  attacker_speed_levels -= 1
                              attacker_speed_roll = random.randint(1,100)
                              if attacker_speed_roll <= attacker_speed_growth:
                                  attacker_speed += 1
                              print(attacker_name + "'s Speed is now " + str(attacker_speed) + ".")
                              
                              # Luck

                              while attacker_luck_levels > 0:
                                  attacker_luck += 1
                                  attacker_luck_levels -= 1
                              attacker_luck_roll = random.randint(1,100)
                              if attacker_luck_roll <= attacker_luck_growth:
                                  attacker_luck += 1
                              print(attacker_name + "'s Luck is now " + str(attacker_luck) + ".")
                              
                              # Defense

                              while attacker_defense_levels > 0:
                                  attacker_defense += 1
                                  attacker_defense_levels -= 1
                              attacker_defense_roll = random.randint(1,100)
                              if attacker_defense_roll <= attacker_defense_growth:
                                  attacker_defense += 1
                              print(attacker_name + "'s Defense is now " + str(attacker_defense) + ".")
                              
                              # Resistance

                              while attacker_resistance_levels > 0:
                                  attacker_resistance += 1
                                  attacker_resistance_levels -= 1
                              attacker_resistance_roll = random.randint(1,100)
                              if attacker_resistance_roll <= attacker_resistance_growth:
                                  attacker_resistance += 1
                              print(attacker_name + "'s Resistance is now " + str(attacker_resistance) + ".")
                          
                      # Attacker kills
              
                      else:
                  
                          # Experience from dealing damage

                          attacker_damage_exp = int((31 + (defender_level + defender_class_bonus_a) - (attacker_level + attacker_class_bonus_a))/attacker_class_power)
                  
                          # Experience from defeating (base)

                          attacker_base_exp = int(((defender_level * defender_class_power) + defender_class_bonus_b) - ((attacker_level * attacker_class_power) + attacker_class_bonus_b))
                  
                          # Experience from defeating enemy

                          attacker_base_defeat_exp = int(attacker_base_exp + 20 + defender_boss_bonus + defender_thief_bonus)
                          if attacker_base_defeat_exp < 0:
                              attacker_base_defeat_exp = 0
                          attacker_defeat_exp = int(attacker_damage_exp + attacker_base_defeat_exp)
                          attacker_exp += attacker_defeat_exp
                          
                          # Leveling up

                          attacker_level_ups = int(attacker_exp/100)
                          attacker_exp -= attacker_level_ups * 100
                          
                          # HP

                          attacker_hp_levels = int(attacker_hp_growth/100)
                          attacker_hp_growth -= attacker_hp_levels * 100
                          
                          # Strength

                          attacker_strength_levels = int(attacker_strength_growth/100)
                          attacker_strength_growth -= attacker_strength_levels * 100
                          
                          # Magic

                          attacker_magic_levels = int(attacker_magic_growth/100)
                          attacker_magic_growth -= attacker_magic_levels * 100
                          
                          # Skill

                          attacker_skill_levels = int(attacker_skill_growth/100)
                          attacker_skill_growth -= attacker_skill_levels * 100
                          
                          # Speed

                          attacker_speed_levels = int(attacker_speed_growth/100)
                          attacker_speed_growth -= attacker_speed_levels * 100
                          
                          # Luck

                          attacker_luck_levels = int(attacker_luck_growth/100)
                          attacker_luck_growth -= attacker_luck_levels * 100
                          
                          # Defense

                          attacker_defense_levels = int(attacker_defense_growth/100)
                          attacker_defense_growth -= attacker_defense_levels * 100
                          
                          # Resistance

                          attacker_resistance_levels = int(attacker_resistance_growth/100)
                          attacker_resistance_growth -= attacker_resistance_levels * 100
                          
                          # Level ups
                          
                          while attacker_level_ups > 0:
                              attacker_level += 1
                              print(attacker_name + " leveled up!")
                              print(attacker_name + "'s level is now " + str(attacker_level) + ".")
                              attacker_level_ups -= 1
                              
                              # HP

                              while attacker_hp_levels > 0:
                                  attacker_max_hp += 1
                                  attacker_hp_levels -= 1
                              attacker_hp_roll = random.randint(1,100)
                              if attacker_hp_roll <= attacker_hp_growth:
                                  attacker_max_hp += 1
                              print(attacker_name + "'s max HP is now " + str(attacker_max_hp) + ".")
                              
                              # Strength

                              while attacker_strength_levels > 0:
                                  attacker_strength += 1
                                  attacker_strength_levels -= 1
                              attacker_strength_roll = random.randint(1,100)
                              if attacker_strength_roll <= attacker_strength_growth:
                                  attacker_strength += 1
                              print(attacker_name + "'s Strength is now " + str(attacker_strength) + ".")
                              
                              # Magic

                              while attacker_magic_levels > 0:
                                  attacker_magic += 1
                                  attacker_magic_levels -= 1
                              attacker_magic_roll = random.randint(1,100)
                              if attacker_magic_roll <= attacker_magic_growth:
                                  attacker_magic += 1
                              print(attacker_name + "'s Magic is now " + str(attacker_magic) + ".")
                              
                              # Skill

                              while attacker_skill_levels > 0:
                                  attacker_skill += 1
                                  attacker_skill_levels -= 1
                              attacker_skill_roll = random.randint(1,100)
                              if attacker_skill_roll <= attacker_skill_growth:
                                  attacker_skill += 1
                              print(attacker_name + "'s Skill is now " + str(attacker_skill) + ".")
                              
                              # Speed

                              while attacker_speed_levels > 0:
                                  attacker_speed += 1
                                  attacker_speed_levels -= 1
                              attacker_speed_roll = random.randint(1,100)
                              if attacker_speed_roll <= attacker_speed_growth:
                                  attacker_speed += 1
                              print(attacker_name + "'s Speed is now " + str(attacker_speed) + ".")
                              
                              # Luck

                              while attacker_luck_levels > 0:
                                  attacker_luck += 1
                                  attacker_luck_levels -= 1
                              attacker_luck_roll = random.randint(1,100)
                              if attacker_luck_roll <= attacker_luck_growth:
                                  attacker_luck += 1
                              print(attacker_name + "'s Luck is now " + str(attacker_luck) + ".")
                              
                              # Defense

                              while attacker_defense_levels > 0:
                                  attacker_defense += 1
                                  attacker_defense_levels -= 1
                              attacker_defense_roll = random.randint(1,100)
                              if attacker_defense_roll <= attacker_defense_growth:
                                  attacker_defense += 1
                              print(attacker_name + "'s Defense is now " + str(attacker_defense) + ".")
                              
                              # Resistance

                              while attacker_resistance_levels > 0:
                                  attacker_resistance += 1
                                  attacker_resistance_levels -= 1
                              attacker_resistance_roll = random.randint(1,100)
                              if attacker_resistance_roll <= attacker_resistance_growth:
                                  attacker_resistance += 1
                              print(attacker_name + "'s Resistance is now " + str(attacker_resistance)  + ".")
                          
                          print(attacker_name + " now has " + str(attacker_exp) + " experience points!")
          
              # Attacker misses

              else:
                  print(attacker_name + " now has " + str(attacker_exp) + " experience points!")
      
          # Attacker is at max level

          else:
              print(attacker_name + " now has " + str(attacker_exp) + " experience points!")

      # Attacker's max level is 20

      else:
          
          if attacker_current_hp > 0:
          
              if attacker_level < 20:
             
                  # Attacker hits
          
                  if attacker_hit_roll <= attacker_accuracy:
              
                      # Attacker doesn't kill

                      if defender_current_hp > 0:
                  
                          # Experience from dealing damage

                          attacker_exp_gained = int((31 + (defender_level + defender_class_bonus_a) - (attacker_level + attacker_class_bonus_a))/attacker_class_power)
                          attacker_exp += attacker_exp_gained
                          
                          # Leveling up

                          attacker_level_ups = int(attacker_exp/100)
                          attacker_exp -= attacker_level_ups * 100
                          
                          # HP

                          attacker_hp_levels = int(attacker_hp_growth/100)
                          attacker_hp_growth -= attacker_hp_levels * 100
                          
                          # Strength

                          attacker_strength_levels = int(attacker_strength_growth/100)
                          attacker_strength_growth -= attacker_strength_levels * 100
                          
                          # Magic

                          attacker_magic_levels = int(attacker_magic_growth/100)
                          attacker_magic_growth -= attacker_magic_levels * 100
                          
                          # Skill

                          attacker_skill_levels = int(attacker_skill_growth/100)
                          attacker_skill_growth -= attacker_skill_levels * 100
                          
                          # Speed

                          attacker_speed_levels = int(attacker_speed_growth/100)
                          attacker_speed_growth -= attacker_speed_levels * 100
                          
                          # Luck

                          attacker_luck_levels = int(attacker_luck_growth/100)
                          attacker_luck_growth -= attacker_luck_levels * 100
                          
                          # Defense

                          attacker_defense_levels = int(attacker_defense_growth/100)
                          attacker_defense_growth -= attacker_defense_levels * 100
                          
                          # Resistance

                          attacker_resistance_levels = int(attacker_resistance_growth/100)
                          attacker_resistance_growth -= attacker_resistance_levels * 100
                          
                          # Level ups

                          while attacker_level_ups > 0:
                              attacker_level += 1
                              print(attacker_name + " leveled up!")
                              print(attacker_name + "'s level is now " + str(attacker_level) + ".")
                              attacker_level_ups -= 1
                              
                              # HP

                              while attacker_hp_levels > 0:
                                  attacker_max_hp += 1
                                  attacker_hp_levels -= 1
                              attacker_hp_roll = random.randint(1,100)
                              if attacker_hp_roll <= attacker_hp_growth:
                                  attacker_max_hp += 1
                              print(attacker_name + "'s max HP is now " + str(attacker_max_hp) + ".")
                              
                              # Strength

                              while attacker_strength_levels > 0:
                                  attacker_strength += 1
                                  attacker_strength_levels -= 1
                              attacker_strength_roll = random.randint(1,100)
                              if attacker_strength_roll <= attacker_strength_growth:
                                  attacker_strength += 1
                              print(attacker_name + "'s Strength is now " + str(attacker_strength) + ".")
                              
                              # Magic

                              while attacker_magic_levels > 0:
                                  attacker_magic += 1
                                  attacker_magic_levels -= 1
                              attacker_magic_roll = random.randint(1,100)
                              if attacker_magic_roll <= attacker_magic_growth:
                                  attacker_magic += 1
                              print(attacker_name + "'s Magic is now " + str(attacker_magic) + ".")
                              
                              # Skill

                              while attacker_skill_levels > 0:
                                  attacker_skill += 1
                                  attacker_skill_levels -= 1
                              attacker_skill_roll = random.randint(1,100)
                              if attacker_skill_roll <= attacker_skill_growth:
                                  attacker_skill += 1
                              print(attacker_name + "'s Skill is now " + str(attacker_skill) + ".")
                              
                              # Speed

                              while attacker_speed_levels > 0:
                                  attacker_speed += 1
                                  attacker_speed_levels -= 1
                              attacker_speed_roll = random.randint(1,100)
                              if attacker_speed_roll <= attacker_speed_growth:
                                  attacker_speed += 1
                              print(attacker_name + "'s Speed is now " + str(attacker_speed) + ".")
                              
                              # Luck

                              while attacker_luck_levels > 0:
                                  attacker_luck += 1
                                  attacker_luck_levels -= 1
                              attacker_luck_roll = random.randint(1,100)
                              if attacker_luck_roll <= attacker_luck_growth:
                                  attacker_luck += 1
                              print(attacker_name + "'s Luck is now " + str(attacker_luck) + ".")
                              
                              # Defense

                              while attacker_defense_levels > 0:
                                  attacker_defense += 1
                                  attacker_defense_levels -= 1
                              attacker_defense_roll = random.randint(1,100)
                              if attacker_defense_roll <= attacker_defense_growth:
                                  attacker_defense += 1
                              print(attacker_name + "'s Defense is now " + str(attacker_defense) + ".")
                              
                              # Resistance

                              while attacker_resistance_levels > 0:
                                  attacker_resistance += 1
                                  attacker_resistance_levels -= 1
                              attacker_resistance_roll = random.randint(1,100)
                              if attacker_resistance_roll <= attacker_resistance_growth:
                                  attacker_resistance += 1
                              print(attacker_name + "'s Resistance is now " + str(attacker_resistance) + ".")
                          
              
                      # Attacker kills
              
                      else:
                  
                          # Experience from dealing damage

                          attacker_damage_exp = int((31 + (defender_level + defender_class_bonus_a) - (attacker_level + attacker_class_bonus_a))/attacker_class_power)
                  
                          # Experience from defeating (base)

                          attacker_base_exp = int(((defender_level * defender_class_power) + defender_class_bonus_b) - ((attacker_level * attacker_class_power) + attacker_class_bonus_b))
                  
                          # Experience from defeating enemy

                          attacker_base_defeat_exp = int(attacker_base_exp + 20 + defender_boss_bonus + defender_thief_bonus)
                          if attacker_base_defeat_exp < 0:
                              attacker_base_defeat_exp = 0
                          attacker_defeat_exp = int(attacker_damage_exp + attacker_base_defeat_exp)
                          attacker_exp += attacker_defeat_exp
                      
                          # Leveling up

                          attacker_level_ups = int(attacker_exp/100)
                          attacker_exp -= attacker_level_ups * 100
                          
                          # HP

                          attacker_hp_levels = int(attacker_hp_growth/100)
                          attacker_hp_growth -= attacker_hp_levels * 100
                          
                          # Strength

                          attacker_strength_levels = int(attacker_strength_growth/100)
                          attacker_strength_growth -= attacker_strength_levels * 100
                          
                          # Magic

                          attacker_magic_levels = int(attacker_magic_growth/100)
                          attacker_magic_growth -= attacker_magic_levels * 100
                          
                          # Skill

                          attacker_skill_levels = int(attacker_skill_growth/100)
                          attacker_skill_growth -= attacker_skill_levels * 100
                          
                          # Speed

                          attacker_speed_levels = int(attacker_speed_growth/100)
                          attacker_speed_growth -= attacker_speed_levels * 100
                          
                          # Luck

                          attacker_luck_levels = int(attacker_luck_growth/100)
                          attacker_luck_growth -= attacker_luck_levels * 100
                          
                          # Defense

                          attacker_defense_levels = int(attacker_defense_growth/100)
                          attacker_defense_growth -= attacker_defense_levels * 100
                          
                          # Resistance

                          attacker_resistance_levels = int(attacker_resistance_growth/100)
                          attacker_resistance_growth -= attacker_resistance_levels * 100
                          
                          # Level ups

                          while attacker_level_ups > 0:
                              attacker_level += 1
                              print(attacker_name + " leveled up!")
                              print(attacker_name + "'s level is now " + str(attacker_level) + ".")
                              attacker_level_ups -= 1
                              
                              # HP

                              while attacker_hp_levels > 0:
                                  attacker_max_hp += 1
                                  attacker_hp_levels -= 1
                              attacker_hp_roll = random.randint(1,100)
                              if attacker_hp_roll <= attacker_hp_growth:
                                  attacker_max_hp += 1
                              print(attacker_name + "'s max HP is now " + str(attacker_max_hp) + ".")
                              
                              # Strength

                              while attacker_strength_levels > 0:
                                  attacker_strength += 1
                                  attacker_strength_levels -= 1
                              attacker_strength_roll = random.randint(1,100)
                              if attacker_strength_roll <= attacker_strength_growth:
                                  attacker_strength += 1
                              print(attacker_name + "'s Strength is now " + str(attacker_strength) + ".")
                              
                              # Magic

                              while attacker_magic_levels > 0:
                                  attacker_magic += 1
                                  attacker_magic_levels -= 1
                              attacker_magic_roll = random.randint(1,100)
                              if attacker_magic_roll <= attacker_magic_growth:
                                  attacker_magic += 1
                              print(attacker_name + "'s Magic is now " + str(attacker_magic) + ".")
                              
                              # Skill

                              while attacker_skill_levels > 0:
                                  attacker_skill += 1
                                  attacker_skill_levels -= 1
                              attacker_skill_roll = random.randint(1,100)
                              if attacker_skill_roll <= attacker_skill_growth:
                                  attacker_skill += 1
                              print(attacker_name + "'s Skill is now " + str(attacker_skill) + ".")
                              
                              # Speed

                              while attacker_speed_levels > 0:
                                  attacker_speed += 1
                                  attacker_speed_levels -= 1
                              attacker_speed_roll = random.randint(1,100)
                              if attacker_speed_roll <= attacker_speed_growth:
                                  attacker_speed += 1
                              print(attacker_name + "'s Speed is now " + str(attacker_speed) + ".")
                              
                              # Luck

                              while attacker_luck_levels > 0:
                                  attacker_luck += 1
                                  attacker_luck_levels -= 1
                              attacker_luck_roll = random.randint(1,100)
                              if attacker_luck_roll <= attacker_luck_growth:
                                  attacker_luck += 1
                              print(attacker_name + "'s Luck is now " + str(attacker_luck) + ".")
                              
                              # Defense

                              while attacker_defense_levels > 0:
                                  attacker_defense += 1
                                  attacker_defense_levels -= 1
                              attacker_defense_roll = random.randint(1,100)
                              if attacker_defense_roll <= attacker_defense_growth:
                                  attacker_defense += 1
                              print(attacker_name + "'s Defense is now " + str(attacker_defense) + ".")
                              
                              # Resistance

                              while attacker_resistance_levels > 0:
                                  attacker_resistance += 1
                                  attacker_resistance_levels -= 1
                              attacker_resistance_roll = random.randint(1,100)
                              if attacker_resistance_roll <= attacker_resistance_growth:
                                  attacker_resistance += 1
                              print(attacker_name + "'s Resistance is now " + str(attacker_resistance) + ".")
                          
                  # Attacker misses

              else:
                  print(attacker_name + " now has " + str(attacker_exp) + " experience points!")
          
          # Attacker is at max level

          else:
              print(attacker_name + " now has " + str(attacker_exp) + " experience points!")

      # Defender
      
      # Defender's max level is 30

      #if attacker_class == "dancer" or attacker_class == "manakete" or attacker_class == "taguel" or attacker_class == "conqueror" or attacker_class == "dread fighter" or attacker_class == "bride" or attacker_class == "villager" or attacker_class == "lodestar" or attacker_class == "soldier" or attacker_class == "merchant" or attacker_class == "revenant" or attacker_class == "entombed" or attacker_class == "grima" or attacker_class == "mirage":
      defender_classes = ["dancer","manakete","taguel","conqueror","dread fighter",
                          "bride","villager","lodestar","soldier","merchant","revenant",
                          "entombed","grima","mirage"]
      if defender_class in defender_classes:


          if defender_current_hp > 0:
         
              if defender_level < 30:
          
                  # Defender hits
          
                  if defender_hit_roll <= defender_accuracy:
              
                      # Defender doesn't kill

                      if attacker_current_hp > 0:
                  
                          # Experience from dealing damage

                          defender_exp_gained = int((31 + (attacker_level + attacker_class_bonus_a) - (defender_level + defender_class_bonus_a))/defender_class_power)
                          defender_exp += defender_exp_gained
                          
                          # Leveling up

                          defender_level_ups = int(defender_exp/100)
                          defender_exp -= defender_level_ups * 100
                          
                          # HP

                          defender_hp_levels = int(defender_hp_growth/100)
                          defender_hp_growth -= defender_hp_levels * 100
                          
                          # Strength

                          defender_strength_levels = int(defender_strength_growth/100)
                          defender_strength_growth -= defender_strength_levels * 100
                          
                          # Magic

                          defender_magic_levels = int(defender_magic_growth/100)
                          defender_magic_growth -= defender_magic_levels * 100
                          
                          # Skill

                          defender_skill_levels = int(defender_skill_growth/100)
                          defender_skill_growth -= defender_skill_levels * 100
                          
                          # Speed

                          defender_speed_levels = int(defender_speed_growth/100)
                          defender_speed_growth -= defender_speed_levels * 100
                          
                          # Luck

                          defender_luck_levels = int(defender_luck_growth/100)
                          defender_luck_growth -= defender_luck_levels * 100
                          
                          # Defense

                          defender_defense_levels = int(defender_defense_growth/100)
                          defender_defense_growth -= defender_defense_levels * 100
                          
                          # Resistance

                          defender_resistance_levels = int(defender_resistance_growth/100)
                          defender_resistance_growth -= defender_resistance_levels * 100
                          
                          # Level ups

                          while defender_level_ups > 0:
                              defender_level += 1
                              print(defender_name + " leveled up!")
                              print(defender_name + "'s level is now " + str(defender_level) + ".")
                              defender_level_ups -= 1
                              
                              # HP

                              while defender_hp_levels > 0:
                                  defender_max_hp += 1
                                  defender_hp_levels -= 1
                              defender_hp_roll = random.randint(1,100)
                              if defender_hp_roll <= defender_hp_growth:
                                  defender_max_hp += 1
                              print(defender_name + "'s max HP is now " + str(defender_max_hp) + ".")
                              
                              # Strength

                              while defender_strength_levels > 0:
                                  defender_strength += 1
                                  defender_strength_levels -= 1
                              defender_strength_roll = random.randint(1,100)
                              if defender_strength_roll <= defender_strength_growth:
                                  defender_strength += 1
                              print(defender_name + "'s Strength is now " + str(defender_strength) + ".")
                              
                              # Magic

                              while defender_magic_levels > 0:
                                  defender_magic += 1
                                  defender_magic_levels -= 1
                              defender_magic_roll = random.randint(1,100)
                              if defender_magic_roll <= defender_magic_growth:
                                  defender_magic += 1
                              print(defender_name + "'s Magic is now " + str(defender_magic) + ".")
                              
                              # Skill

                              while defender_skill_levels > 0:
                                  defender_skill += 1
                                  defender_skill_levels -= 1
                              defender_skill_roll = random.randint(1,100)
                              if defender_skill_roll <= defender_skill_growth:
                                  defender_skill += 1
                              print(defender_name + "'s Skill is now " + str(defender_skill) + ".")
                              
                              # Speed

                              while defender_speed_levels > 0:
                                  defender_speed += 1
                                  defender_speed_levels -= 1
                              defender_speed_roll = random.randint(1,100)
                              if defender_speed_roll <= defender_speed_growth:
                                  defender_speed += 1
                              print(defender_name + "'s Speed is now " + str(defender_speed) + ".")
                              
                              # Luck

                              while defender_luck_levels > 0:
                                  defender_luck += 1
                                  defender_luck_levels -= 1
                              defender_luck_roll = random.randint(1,100)
                              if defender_luck_roll <= defender_luck_growth:
                                  defender_luck += 1
                              print(defender_name + "'s Luck is now " + str(defender_luck) + ".")
                              
                              # Defense

                              while defender_defense_levels > 0:
                                  defender_defense += 1
                                  defender_defense_levels -= 1
                              defender_defense_roll = random.randint(1,100)
                              if defender_defense_roll <= defender_defense_growth:
                                  defender_defense += 1
                              print(defender_name + "'s Defense is now " + str(defender_defense) + ".")
                              
                              # Resistance

                              while defender_resistance_levels > 0:
                                  defender_resistance += 1
                                  defender_resistance_levels -= 1
                              defender_resistance_roll = random.randint(1,100)
                              if defender_resistance_roll <= defender_resistance_growth:
                                  defender_resistance += 1
                              print(defender_name + "'s Resistance is now " + str(defender_resistance) + ".")
                          
                      # Defender kills
              
                      else:
                  
                          # Experience from dealing damage

                          defender_damage_exp = int((31 + (attacker_level + attacker_class_bonus_a) - (defender_level + defender_class_bonus_a))/defender_class_power)
                  
                          # Experience from defeating (base)

                          attacker_base_exp = int(((attacker_level * attacker_class_power) + attacker_class_bonus_b) - ((defender_level * defender_class_power) + defender_class_bonus_b))
                  
                          # Experience from defeating enemy

                          defender_base_defeat_exp = int(defender_base_exp + 20 + attacker_boss_bonus + attacker_thief_bonus)
                          if defender_base_defeat_exp < 0:
                              defender_base_defeat_exp = 0
                          defender_defeat_exp = int(defender_damage_exp + defender_base_defeat_exp)
                          defender_exp += defender_defeat_exp
                          
                          # Leveling up

                          defender_level_ups = int(defenderr_exp/100)
                          defender_exp -= defender_level_ups * 100
                          
                          # HP

                          defender_hp_levels = int(defender_hp_growth/100)
                          defender_hp_growth -= defender_hp_levels * 100
                          
                          # Strength

                          defender_strength_levels = int(defender_strength_growth/100)
                          defender_strength_growth -= defender_strength_levels * 100
                          
                          # Magic

                          defender_magic_levels = int(defender_magic_growth/100)
                          defender_magic_growth -= defender_magic_levels * 100
                          
                          # Skill

                          defender_skill_levels = int(defender_skill_growth/100)
                          defender_skill_growth -= defender_skill_levels * 100
                          
                          # Speed

                          defender_speed_levels = int(defender_speed_growth/100)
                          defender_speed_growth -= defender_speed_levels * 100
                          
                          # Luck

                          defender_luck_levels = int(defender_luck_growth/100)
                          defender_luck_growth -= defender_luck_levels * 100
                          
                          # Defense

                          defender_defense_levels = int(defender_defense_growth/100)
                          defender_defense_growth -= defender_defense_levels * 100
                          
                          # Resistance

                          defender_resistance_levels = int(defender_resistance_growth/100)
                          defender_resistance_growth -= defender_resistance_levels * 100
                          
                          # Level ups

                          while defender_level_ups > 0:
                              defender_level += 1
                              print(defender_name + " leveled up!")
                              print(defender_name + "'s level is now " + str(defender_level) + ".")
                              defender_level_ups -= 1
                              
                              # HP

                              while defender_hp_levels > 0:
                                  defender_max_hp += 1
                                  defender_hp_levels -= 1
                              defender_hp_roll = random.randint(1,100)
                              if defender_hp_roll <= defender_hp_growth:
                                  defender_max_hp += 1
                              print(defender_name + "'s max HP is now " + str(defender_max_hp) + ".")
                              
                              # Strength

                              while defender_strength_levels > 0:
                                defender_strength += 1
                                defender_strength_levels -= 1
                              defender_strength_roll = random.randint(1,100)
                              if defender_strength_roll <= defender_strength_growth:
                                  defender_strength += 1
                              print(defender_name + "'s Strength is now " + str(defender_strength) + ".")
                              
                              # Magic

                              while defender_magic_levels > 0:
                                  defender_magic += 1
                                  defender_magic_levels -= 1
                              defender_magic_roll = random.randint(1,100)
                              if defender_magic_roll <= defender_magic_growth:
                                  defender_magic += 1
                              print(defender_name + "'s Magic is now " + str(defender_magic) + ".")
                              
                              # Skill

                              while defender_skill_levels > 0:
                                  defender_skill += 1
                                  defender_skill_levels -= 1
                              defender_skill_roll = random.randint(1,100)
                              if defender_skill_roll <= defender_skill_growth:
                                  defender_skill += 1
                              print(defender_name + "'s Skill is now " + str(defender_skill) + ".")
                              
                              # Speed

                              while defender_speed_levels > 0:
                                  defender_speed += 1
                                  defender_speed_levels -= 1
                              defender_speed_roll = random.randint(1,100)
                              if defender_speed_roll <= defender_speed_growth:
                                  defender_speed += 1
                              print(defender_name + "'s Speed is now "+ str(defender_speed) + ".")
                              
                              # Luck

                              while defender_luck_levels > 0:
                                  defender_luck += 1
                                  defender_luck_levels -= 1
                              defender_luck_roll = random.randint(1,100)
                              if defender_luck_roll <= defender_luck_growth:
                                  defender_luck += 1
                              print(defender_name + "'s Luck is now " + str(defender_luck) + ".")
                              
                              # Defense

                              while defender_defense_levels > 0:
                                  defender_defense += 1
                                  defender_defense_levels -= 1
                              defender_defense_roll = random.randint(1,100)
                              if defender_defense_roll <= defender_defense_growth:
                                  defender_defense += 1
                              print(defender_name + "'s Defense is now " + str(defender_defense) + ".")
                              
                              # Resistance

                              while defender_resistance_levels > 0:
                                  defender_resistance += 1
                                  defender_resistance_levels -= 1
                              defender_resistance_roll = random.randint(1,100)
                              if defender_resistance_roll <= defender_resistance_growth:
                                  defender_resistance += 1
                              print(defender_name + "'s Resistance is now " + str(defender_resistance)  + ".")
                          
                          print(defender_name + " now has " + str(defender_exp) + " experience points!")
          
              # Defender misses

              else:
                  print(defender_name + " now has " + str(defender_exp) + " experience points!")
      
          # Defender is at max level

          else:
              print(defender_name + " now has " + str(defender_exp) + " experience points!")

      # Defender's max level is 20

      else:
          
          if defender_current_hp > 0:
          
              if defender_level < 20:
             
                  # Defender hits
          
                  if defender_hit_roll <= defender_accuracy:
              
                      # Defender doesn't kill

                      if attacker_current_hp > 0:
                  
                          # Experience from dealing damage

                          defender_exp_gained = int((31 + (attacker_level + attacker_class_bonus_a) - (defender_level + defender_class_bonus_a))/defender_class_power)
                          defender_exp += defender_exp_gained
                          
                          # Leveling up

                          defender_level_ups = int(defender_exp/100)
                          defender_exp -= defender_level_ups * 100
                          
                          # HP

                          defender_hp_levels = int(defender_hp_growth/100)
                          defender_hp_growth -= defender_hp_levels * 100
                          
                          # Strength

                          defender_strength_levels = int(defender_strength_growth/100)
                          defender_strength_growth -= defender_strength_levels * 100
                          
                          # Magic

                          defender_magic_levels = int(defender_magic_growth/100)
                          defender_magic_growth -= defender_magic_levels * 100
                          
                          # Skill

                          defender_skill_levels = int(defender_skill_growth/100)
                          defender_skill_growth -= defender_skill_levels * 100
                          
                          # Speed

                          defender_speed_levels = int(defender_speed_growth/100)
                          defender_speed_growth -= defender_speed_levels * 100
                          
                          # Luck

                          defender_luck_levels = int(defender_luck_growth/100)
                          defender_luck_growth -= defender_luck_levels * 100
                          
                          # Defense

                          defender_defense_levels = int(defender_defense_growth/100)
                          defender_defense_growth -= defender_defense_levels * 100
                          
                          # Resistance

                          defender_resistance_levels = int(defender_resistance_growth/100)
                          defender_resistance_growth -= defender_resistance_levels * 100
                          
                          # Level ups

                          while defender_level_ups > 0:
                              defender_level += 1
                              print(defender_name + " leveled up!")
                              print(defender_name + "'s level is now " + str(defender_level) + ".")
                              defender_level_ups -= 1
                              
                              # HP

                              while defender_hp_levels > 0:
                                  defender_max_hp += 1
                                  defender_hp_levels -= 1
                              defender_hp_roll = random.randint(1,100)
                              if defender_hp_roll <= defender_hp_growth:
                                  defender_max_hp += 1
                              print(defender_name + "'s max HP is now " + str(defender_max_hp) + ".")
                              
                              # Strength

                              while defender_strength_levels > 0:
                                  defender_strength += 1
                                  defender_strength_levels -= 1
                              defender_strength_roll = random.randint(1,100)
                              if defender_strength_roll <= defender_strength_growth:
                                  defender_strength += 1
                              print(defender_name + "'s Strength is now " + str(defender_strength) + ".")
                              
                              # Magic

                              while defender_magic_levels > 0:
                                  defender_magic += 1
                                  defender_magic_levels -= 1
                              defender_magic_roll = random.randint(1,100)
                              if defender_magic_roll <= defender_magic_growth:
                                  defender_magic += 1
                              print(defender_name + "'s Magic is now " + str(defender_magic) + ".")
                              
                              # Skill

                              while defender_skill_levels > 0:
                                  defender_skill += 1
                                  defender_skill_levels -= 1
                              defender_skill_roll = random.randint(1,100)
                              if defender_skill_roll <= defender_skill_growth:
                                  defender_skill += 1
                              print(defender_name + "'s Skill is now " + str(defender_skill) + ".")
                              
                              # Speed

                              while defender_speed_levels > 0:
                                  defender_speed += 1
                                  defender_speed_levels -= 1
                              defender_speed_roll = random.randint(1,100)
                              if defender_speed_roll <= defender_speed_growth:
                                  defender_speed += 1
                              print(defender_name + "'s Speed is now " + str(defender_speed) + ".")
                              
                              # Luck

                              while defender_luck_levels > 0:
                                  defender_luck += 1
                                  defender_luck_levels -= 1
                              defender_luck_roll = random.randint(1,100)
                              if defender_luck_roll <= defender_luck_growth:
                                  defender_luck += 1
                              print(defender_name + "'s Luck is now " + str(defender_luck) + ".")
                              
                              # Defense

                              while defender_defense_levels > 0:
                                  defender_defense += 1
                                  defender_defense_levels -= 1
                              defender_defense_roll = random.randint(1,100)
                              if defender_defense_roll <= defender_defense_growth:
                                  defender_defense += 1
                              print(defender_name + "'s Defense is now " + str(defender_defense) + ".")
                              
                              # Resistance

                              while defender_resistance_levels > 0:
                                  defender_resistance += 1
                                  defender_resistance_levels -= 1
                              defender_resistance_roll = random.randint(1,100)
                              if defender_resistance_roll <= defender_resistance_growth:
                                  defender_resistance += 1
                              print(defender_name + "'s Resistance is now " + str(defender_resistance) + ".")
                          
              
                      # Defender kills
              
                      else:
                  
                          # Experience from dealing damage

                          defender_damage_exp = int((31 + (attacker_level + attacker_class_bonus_a) - (defender_level + defender_class_bonus_a))/defender_class_power)
                  
                          # Experience from defeating (base)

                          defender_base_exp = int(((attacker_level * attacker_class_power) + attacker_class_bonus_b) - ((defender_level * defender_class_power) + defender_class_bonus_b))
                  
                          # Experience from defeating enemy

                          defender_base_defeat_exp = int(defender_base_exp + 20 + attacker_boss_bonus + attacker_thief_bonus)
                          if defender_base_defeat_exp < 0:
                              defender_base_defeat_exp = 0
                          defender_defeat_exp = int(defender_damage_exp + defender_base_defeat_exp)
                          defender_exp += defender_defeat_exp
                      
                          # Leveling up

                          defender_level_ups = int(defender_exp/100)
                          defender_exp -= defender_level_ups * 100
                          
                          # HP

                          defender_hp_levels = int(defender_hp_growth/100)
                          defender_hp_growth -= defender_hp_levels * 100
                          
                          # Strength

                          defender_strength_levels = int(defender_strength_growth/100)
                          defender_strength_growth -= defender_strength_levels * 100
                          
                          # Magic

                          defender_magic_levels = int(defender_magic_growth/100)
                          defender_magic_growth -= defender_magic_levels * 100
                          
                          # Skill

                          defender_skill_levels = int(defender_skill_growth/100)
                          defender_skill_growth -= defender_skill_levels * 100
                          
                          # Speed

                          defender_speed_levels = int(defender_speed_growth/100)
                          defender_speed_growth -= defender_speed_levels * 100
                          
                          # Luck

                          defender_luck_levels = int(defender_luck_growth/100)
                          defender_luck_growth -= defender_luck_levels * 100
                          
                          # Defense

                          defender_defense_levels = int(defender_defense_growth/100)
                          defender_defense_growth -= defender_defense_levels * 100
                          
                          # Resistance

                          defender_resistance_levels = int(defender_resistance_growth/100)
                          defender_resistance_growth -= defender_resistance_levels * 100
                          
                          # Level ups

                          while defender_level_ups > 0:
                              defender_level += 1
                              print(defender_name + " leveled up!")
                              print(defender_name + "'s level is now " + str(defender_level) + ".")
                              defender_level_ups -= 1
                              
                              # HP

                              while defender_hp_levels > 0:
                                  defender_max_hp += 1
                                  defender_hp_levels -= 1
                              defender_hp_roll = random.randint(1,100)
                              if defender_hp_roll <= defender_hp_growth:
                                  defender_max_hp += 1
                              print(defender_name + "'s max HP is now " + str(defender_max_hp) + ".")
                              
                              # Strength

                              while defender_strength_levels > 0:
                                  defender_strength += 1
                                  defender_strength_levels -= 1
                              defender_strength_roll = random.randint(1,100)
                              if defender_strength_roll <= defender_strength_growth:
                                  defender_strength += 1
                              print(defender_name + "'s Strength is now " + str(defender_strength) + ".")
                              
                              # Magic

                              while defender_magic_levels > 0:
                                  defender_magic += 1
                                  defender_magic_levels -= 1
                              defender_magic_roll = random.randint(1,100)
                              if defender_magic_roll <= defender_magic_growth:
                                  defender_magic += 1
                              print(defender_name + "'s Magic is now " + str(defender_magic) + ".")
                              
                              # Skill

                              while defender_skill_levels > 0:
                                  defender_skill += 1
                                  defender_skill_levels -= 1
                              defender_skill_roll = random.randint(1,100)
                              if defender_skill_roll <= defender_skill_growth:
                                  defender_skill += 1
                              print(defender_name + "'s Skill is now " + str(defender_skill) + ".")
                              
                              # Speed

                              while defender_speed_levels > 0:
                                  defender_speed += 1
                                  defender_speed_levels -= 1
                              defender_speed_roll = random.randint(1,100)
                              if defender_speed_roll <= defender_speed_growth:
                                  defender_speed += 1
                              print(defender_name + "'s Speed is now " + str(defender_speed) + ".")
                              
                              # Luck

                              while defender_luck_levels > 0:
                                  defender_luck += 1
                                  defender_luck_levels -= 1
                              defender_luck_roll = random.randint(1,100)
                              if defender_luck_roll <= defender_luck_growth:
                                  defender_luck += 1
                              print(defender_name + "'s Luck is now " + str(defender_luck) + ".")
                              
                              # Defense

                              while defender_defense_levels > 0:
                                  defender_defense += 1
                                  defender_defense_levels -= 1
                              defender_defense_roll = random.randint(1,100)
                              if defender_defense_roll <= defender_defense_growth:
                                  defender_defense += 1
                              print(defender_name + "'s Defense is now " + str(defender_defense) + ".")
                              
                              # Resistance
                              
                              while defender_resistance_levels > 0:
                                  defender_resistance += 1
                                  defender_resistance_levels -= 1
                              defender_resistance_roll = random.randint(1,100)
                              if defender_resistance_roll <= defender_resistance_growth:
                                  defender_resistance += 1
                              print(defender_name + "'s Resistance is now " + str(defender_resistance) + ".")
                  
                  # Defender misses
              
                else:
                  print(defender_name + " now has " + str(defender_exp) + " experience points!")
          
          # Defender is at max level
          
        else:
          print(defender_name + " now has " + str(defender_exp) + " experience points!")
